### ISSUE TITLE
iPython crashes when hitting TAB to find an object of type bottlenose.Amazon properties

### ISSUE THREAD

**Issue by mraltman** [lionheart/bottlenose#15]
Using iPython 0.11 and Python 2.7.

I'm doing the following in iPython:

``` python
a = bottlenose.Amazon(AMAZON_ACCESS_KEY_ID, AMAZON_SECRET_KEY, AMAZON_ASSOC_TAG)
a.
```

After typing `a.` I hit TAB and iPython crashes

```
a.ERROR: An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (14, 0)) 
```

**Comment by dlo** [comment]
Unsure if this has been resolved, but it's been such a long time that if it comes up again, I suggest you comment here and I'll reopen the issue. :)
