### ISSUE TITLE
Change API version to 2013-08-01 

### ISSUE THREAD

**Issue by ckazel** [lionheart/bottlenose#34]
Amazon document indicates that current version is 2013-08-01 and best practices document advice to use latest version.

"The Product Advertising API uses the default API version 2013-08-01 unless you supply a different value for the Version parameter. To use a different version, you must include it in the Version parameter in your requests."
[Amazon Advertising API Best Practices] (http://docs.aws.amazon.com/AWSECommerceService/latest/DG/CHAP_BestProgrammingPractices.html)

**Comment by Stephn-R** [comment]
Can you provide more details on what it is you are requesting?

**Comment by ckazel** [comment]
Hi, I am new to Amazon Advertising API, this is what I understand : changing Version parameter will be enough in following API code.
```python
class Amazon(AmazonCall):
    def __init__(self, AWSAccessKeyId=None, AWSSecretAccessKey=None,
            AssociateTag=None, Operation=None, Version="2011-08-01",
            Region="US", Timeout=None, MaxQPS=None, Parser=None,
            CacheReader=None, CacheWriter=None, ErrorHandler=None):
```
