### ISSUE TITLE
A release?

### ISSUE THREAD

**Issue by mafrosis** [lionheart/bottlenose#41]
Hey any chance of a point release? I just revisited a project and had to debug an issue with HMAC and unicode.. Only to discover I fixed this already 6 months ago :D 

3ff57a238aab8ff17206b22a02374109ae4f3dad

**Comment by Stephn-R** [comment]
I can push a new build release but lets chime in with @dlo first

**Comment by dlo** [comment]
@Stephn-R Sounds great, just let me know when to do that sdist upload and I'll get it done. :)

**Comment by mafrosis** [comment]
Thanks dudes!

**Comment by dlo** [comment]
Think this was taken care of a while back.

**Comment by mafrosis** [comment]
It was! 👍
