### ISSUE TITLE
cache example

### ISSUE THREAD

**Issue by ilmetu** [lionheart/bottlenose#43]
Hi, i try to use the cache function with bottlenose ...

```python
def reader(cache_url):
    return cache.ram(cache_url,lambda: None,time_expire=86400) #Time expire can be any value you want (3600 = 1hour)

def writer(cache_url, response_text):
    cache.ram(cache_url,lambda: response_text,time_expire=0) #Time Expire always 0 here
```

i'm very new to python and i don't know what to import for the chache.ram function :(

can you help me ?

Thanks

**Comment by ilmetu** [comment]
anybody here ???

**Comment by dlo** [comment]
This is just an arbitrary example, but you can swap in these functions for any cache backend you want (e.g., Redis, memcached, etc.).
