### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by alexington** [lionheart/bottlenose#50]
Hi,

According to https://caniusepython3.com/project/bottlenose, this package does not support Python 3.

Is that correct?  There seem to be some Python 3 related commits here, but I am not sure how to check if this project as a whole is Python 3 compatible.

Thanks!

**Comment by xtream1101** [comment]
@alexington I have been using bottlenose with python 3.4.x & 3.5.x for a few months and have not had any problems with it.

**Comment by dlo** [comment]
Thanks @xtream1101! Will go ahead and mark as compatible with Python 3.4/3.5.
