### ISSUE TITLE
Product Advertising API Amazon

### ISSUE THREAD

**Issue by vovanduc** [lionheart/bottlenose#57]
**Hi,**

My name is Duc, my job is developer website. I need a Product Advertising API Associate account, but I can not register because I do not have an online shop. I just need it to get the products of amazon. You can sell or share account Associate ?

Sorry for my English is not good

**Thanks!**

**Comment by MichaelHugh** [comment]
it is not difficult to crate a buyer account

**Comment by dlo** [comment]
Please ask this on StackOverflow and post question URL in a follow-up comment. There is a "bottlenose" tag that you can use to categorize the question. See https://github.com/lionheart/bottlenose#communication for more information.
