### ISSUE TITLE
Help needed regarding AWS IAM for using bottlenose

### ISSUE THREAD

**Issue by tanmay-kulkarni** [lionheart/bottlenose#58]
Forgive me for asking this here, as this is not really an issue with the code.
I want to know what AWS IAM permissions are needed to allow using bottlenose. I created a user in AWS IAM and gave him some permissions, but when I tried using bottlenose I get an error 'Unauthorized 401'.

So what permissions should I give the user for querying products using bottlenose?

Thank you

**Comment by dlo** [comment]
Please ask this on StackOverflow and post question URL in a follow-up comment. There is a "bottlenose" tag that you can use to categorize the question. See https://github.com/lionheart/bottlenose#communication for more information.
