### ISSUE TITLE
Change Marketplace

### ISSUE THREAD

**Issue by abhilash1in** [lionheart/bottlenose#60]
Associate ID and access to the API is restricted to the Marketplace (Locale) in which the Associate account was registered. How to change the Marketplace/Locale in this wrapper? For example: I can only access the Indian Market place since I've created an associate account there.

**Comment by golightlyb** [comment]
Hi, just specify Region as a named-argument in your constructor:

    amazon = bottlenose.Amazon('AAWSAccessKeyId, AWSSecretAccessKey, AssociateTag, Region='IN')

The possible values for `Region` are

    CA, CN, DE, ES, FR, IN, IT, JP, UK, US, BR, MX

**Comment by dlo** [comment]
Thanks @golightlyb!

@abhilash1in in the future, please follow the instructions in the README and ask questions like this on StackOverflow. 👍
