### ISSUE TITLE
Add Region to examples

### ISSUE THREAD

**Issue by bambax** [lionheart/bottlenose#63]
Maybe it's just me but it took me some time to figure out that to set endpoints one simply has to add Region to the request, as such:

    amazon = bottlenose.Amazon(AWS_KEY, AWS_SECRET, AWS_TAG, Region='FR')

Could this maybe be added in the tutorial somewhere?

**Comment by dlo** [comment]
Absolutely—would you be willing to submit a PR?

**Comment by bambax** [comment]
Yes ok thanks, I just did.
