### ISSUE TITLE
Inconsistent querying with 503 Errors

### ISSUE THREAD

**Issue by DDiran** [lionheart/bottlenose#68]
Hi there,

I've been playing around with bottlenose, using a forloop to loop over products on my website and check whether prices are up to date.

The issue is that I've been experiencing `503` errors, but in a totally random sequence. Sometimes I run the command and it works, other times it doesn't work, and sometimes it works for a few loops and then throws the error. I have experimented extensively with tweaking the `MaxQPS` settings and the only time it works consistently is when `MaxQPS=0.1` but this is devilishly slow, especially when I'm having to query hundreds of items.

Any idea why this could be? Thanks in advance

(P.S. Awesome work on bottlenose, it's top notch!)

**EDIT** Naturally, now that I have posted this, the `MaxQPS=0.1` is also now acting inconsistently, occasionally throwing 503 errors! *Sigh*

**Comment by ajohnclark** [comment]
I'm getting a lot of random connections timed out and reset by peer errors doing a similar loop. Doing manual sleep() of 1-3 seconds, even tried over a 60 seconds and it still happens randomly. Seems to work okay on Amazon's scratchpad when I'm testing with direct URLs. This started about 2-3 days ago but was working perfectly otherwise. Tried updating lib too and didn't fix.

**Comment by dlo** [comment]
This seems like it's an AWS API issue. Have you checked the forum to see if anyone else is running into this?

**Comment by ajohnclark** [comment]
I think it was an AWS API issue like you said, saw one comment on forum about it. S3 was timing out last evening too for me. Today, Both S3/Product Ad. API working without hiccups. Thanks for great lib.

**Comment by dlo** [comment]
Glad you've found it useful! 503s are generally a sign of an API issue. Maybe a more descriptive error message from Bottlenose would be helpful for diagnosing in the future?

**Comment by ajohnclark** [comment]
Could be a 'nice to have' - was a little harder to debug than normal but no biggie, thanks again and have a great week!

**Comment by DDiran** [comment]
Awesome, thanks guys!
