### ISSUE TITLE
Support for Amazon AU

### ISSUE THREAD

**Issue by someidiot** [lionheart/bottlenose#69]
Amazon just opened a store in Australia. Can we please get support for AU. Currently getting the error when I try:

```python
  File "/home/nathan/venv_rb/lib/python3.4/site-packages/bottlenose/api.py", line 252, in __call__
    cache_url = self.cache_url(**kwargs)
  File "/home/nathan/venv_rb/lib/python3.4/site-packages/bottlenose/api.py", line 209, in cache_url
    service_domain = SERVICE_DOMAINS[self.Region][0]
KeyError: 'AU'
```

**Comment by dlo** [comment]
Can you paste the command you're trying to run?

**Comment by someidiot** [comment]
I'm using https://github.com/yoavaviram/python-amazon-simple-product-api which in turn uses bottlenose.

When instantiating a AmazonAPI() class it in turn calls bottlenose.Amazon(aws_key, aws_secret, aws_associate_tag, **kwargs)

I am passing region='AU' and getting this error which I traced back to the above call stack.

**Comment by Sorkanius** [comment]
AU is not supported, as the README says. I suggest that you add a new line in the SERVICE_DOMAINS dictionary in the file api.py.

Hope it helps.

**Comment by dlo** [comment]
Australia isn't officially supported by Amazon. When it is we can reopen this issue. For now, there isn't a workaround, unfortunately. http://docs.aws.amazon.com/AWSECommerceService/latest/DG/Locales.html

**Comment by dlo** [comment]
<img width="470" alt="screen shot 2017-12-13 at 9 32 04 am" src="https://user-images.githubusercontent.com/38447/33946862-830d4096-dfe8-11e7-901a-6909b7114304.png">

**Comment by pratesbh** [comment]
Amazon AU api was [officially released](https://affiliate-program.amazon.com.au/welcome/topic/tools/ref=amb_link_y6_PqsV4PvWWDWi9wZVAeA_5?pf_rd_p=3acc10f8-3d4a-4dcb-92c6-a9d6db22755d)!
