### ISSUE TITLE
exception HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by galeone** [lionheart/bottlenose#74]
Hi all,

I'm using your library to lookup in the Amazon database using the ASIN, I'm using the same code for 3 different regions (using 2 API keys, one for a region and one shared by 2 regions) and until today everything worked fine.

However, starting from today, the requests made with the API key shared among the 2 regions raise the exception: `HTTP Error 400: Bad Request`.

This sounds really strange to me since the same code worked until yesterday and the same code still work for the other region with the other API key.

This is the call:

```
region.amazon.ItemLookup(ItemId=keyword, IdType="ASIN", ResponseGroup="ItemAttributes,Offers,Images")
```

It's strange also because it doesn't' raise an exception with status code 502 or 503 (too many requests, it would make sense), but a 400.

Any idea?
Thanks

**Comment by dlo** [comment]
This looks like an Amazon API issues. Please ask this on StackOverflow and post the question URL in a follow-up comment. There is a "bottlenose" tag that you can use to categorize the question. See https://github.com/lionheart/bottlenose#communication for more information. Thanks! 👍
